language: php

php:
  - 7.3
  - 7.4

script:
  - composer install
  - ./vendor/bin/phpunit

after_success:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - travis_retry php ./vendor/bin/coveralls -v
