language: php

php:
  - 7.3
  - 8.0

script:
  - composer install
  - ./vendor/bin/phpunit

after_success:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - travis_retry ./vendor/bin/php-coveralls --exclude-no-stmt -v
