language: php

matrix:
  include:
    - php: 7.2
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.8.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.8.*

script:
  - composer install
  - ./vendor/bin/phpunit

after_success:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - travis_retry php ./vendor/bin/coveralls -v
